name: tenant_iac_deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to deploy'
        required: true
        default: dev
        options:
          - dev
          - qa

      region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1
          - eu-central-1

      working_directory:
        type: string
        description: 'Folder to run Terraform'
        required: true
        default: tenant_iac

jobs:

  Plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.role }}
          role-skip-session-tagging: true
          aws-region: ${{ inputs.region }}
          role-duration-seconds: 3600

      - name: Terraform Initialize
        run: terraform init \
          -backend-config=backend/${{ inputs.region }}/${{ inputs.environment }}.s3.backend \
          -input=false \
          -var-file=variables/${{ inputs.region }}/${{ inputs.environment }}.tfvars

      - name: Terraform Plan
        run: terraform plan \
          -var-file=variables/${{ inputs.region }}/${{ inputs.environment }}.tfvars \
          -out=tfplan


  Approval:
    runs-on: ubuntu-latest
    needs: [Plan]
    environment: approval-${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


  Apply:
    runs-on: ubuntu-latest
    needs: [Approval]
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.role }}
          role-skip-session-tagging: true
          aws-region: ${{ inputs.region }}
          role-duration-seconds: 3600

      - name: Terraform Initialize
        run: terraform init \
          -backend-config=backend/${{ inputs.region }}/${{ inputs.environment }}.s3.backend \
          -input=false \
          -var-file=variables/${{ inputs.region }}/${{ inputs.environment }}.tfvars

      - name: Terraform Apply
        env:
          TF_VAR_region: ${{ inputs.region }}
          TF_VAR_environment: ${{ inputs.environment }}
        run: terraform apply \
          -input=false \
          -var-file=variables/${{ inputs.region }}/${{ inputs.environment }}.tfvars \
          -auto-approve
